### ISSUE TITLE
issue in rendering

### ISSUE THREAD

**Issue by husseinraed** [remance/Masendor#11]
in ur game a scene is being rendered above the other scene wich may be annoying i think we can fix this easily ill see if i can fix it if someone is already fixing it please comment so we dont have any conflicts in the code

**Comment by husseinraed** [comment]
i dont think this is rly important until now

**Comment by remance** [comment]
What do you mean by rendered above the other scene? during the main menu or battle or just how the game rendered in general?

**Comment by husseinraed** [comment]
like for example when in the menu i press this occurs and also i cant see the start button 
![image](https://user-images.githubusercontent.com/61946274/107975367-1072ca00-6fc9-11eb-8308-72715b9ff351.png)

**Comment by husseinraed** [comment]
i think this is happening because your drawing the buttons before the details screen wich triggers this issue this on smaller screens

**Comment by husseinraed** [comment]
thats wat i meant if i increase my res a bit i can see half of the start button but its underthe details pane

**Comment by remance** [comment]
oh ok, that look really weird. yeah, it is very likely the issue with a smaller screen. I will see what I can do

**Comment by husseinraed** [comment]
i think its pretty easy just draw the buttons above the details pane

**Comment by husseinraed** [comment]
oh wait i jsut realized thats not the issue of drawing its the issue of the screen size

**Comment by husseinraed** [comment]
to fix this one of the approaches is making the details pane smaller

**Comment by husseinraed** [comment]
depending on the screen size

**Comment by remance** [comment]
yeah, I did that for the most sprite in the menu already, guess I forgot to add that to the details pane.

**Comment by remance** [comment]
what is your screen resolution, if you don't mind telling?

**Comment by husseinraed** [comment]
yes its not a big problem btw, congrats ur game is rly good but tbh i cant find out how to play it correctly i think u have to finish the enclopyedia screen huuh i cant spell it correctly

**Comment by husseinraed** [comment]
yes wiat
its about 1024 by 600

**Comment by husseinraed** [comment]
wait ill tell u exact numbers

**Comment by husseinraed** [comment]
its 1920x1080 but i set the game screen to 1024x600 cuz none of the default resolutions are working for me

**Comment by remance** [comment]
weird, when you say not working. The game simply can't start at a higher resolution? or just you can't change it.

**Comment by husseinraed** [comment]
no no no it works but its higher than my screen

**Comment by remance** [comment]
Well, that quite an unexpected problem. As it works fine for me on all option. I will see what I can do about this.

And yeah I will work on the manual/tutorial at some point. Mostly working on getting the main function to work right now. I will probably begin adding on that in version 0.7.

**Comment by remance** [comment]
maybe adding fullscreen option will help a bit

**Comment by husseinraed** [comment]
yes all options work with u cuz i think ur using a high res screen but my screen is a bit low res

**Comment by remance** [comment]
ok, I try update a quick fix for this but no idea how it will really help. really tough working on the compatibility issue with only a laptop in hand :l

**Comment by remance** [comment]
At least the button will always show up above the detail pane now I think. even if the UI scale looks ugly. I wonder why it look so weird on your screen though. my laptop also uses 1920 x1080 screen resolution (but it has 3840 x 2160 recommended). I will try look for other people to check this issue to see what the real issue is.

**Comment by husseinraed** [comment]
i think its the issue with sprite sizes

**Comment by husseinraed** [comment]
the best fix in my opinion is changing the sprite size depending on the screen size

**Comment by husseinraed** [comment]
i mean window size*

**Comment by remance** [comment]
I already did that though. But I use the number from the configuration file instead of pygame. I am thinking that maybe the real issue is where your pygame automatically scale the window based on your screen so it no longer matches the scale number option.

**Comment by husseinraed** [comment]
yes i think thats a good idea

**Comment by husseinraed** [comment]
u can implemnt it easily in fact i wnated to do that and puch a pull request but i cant rly find where the window setup code rly is

**Comment by remance** [comment]
I am on it. but if you want to have a look, it would be in main.py at line 36 (that get config resolution number) and line 135 (where the display is setup)

**Comment by remance** [comment]
My guess is the pygame.RESIZABLE flag in pygame.display.set_mode at line 136 that cause this issue but I can't really confirm it. Unless you can try delete this part and test, I will need to try to test on the virtual machine and see if it related.

**Comment by husseinraed** [comment]
thats not related at all in fact when u resize it just puts the content of the window in the corner and everything stays the same size but we can do is using the screen info library check the users screen size and depending on that we set the default resolution that suits that screen size

**Comment by husseinraed** [comment]
so wait will u work on it or do i cuz i dont think u will enjoy any conflicts

**Comment by remance** [comment]
It will be hard for me to check if I really fix or not on my end. So if you can fix it then yes please. and thanks a lot.

**Comment by husseinraed** [comment]
np ok ill work on it will take a few minutes anyways

testing it is easy just go to ur os settings and try different screen resolutions and see if it works

**Comment by remance** [comment]
I have tried changing to various in the os setting from 3840 x 2160 to 1280 x 720. And can't seem to replicate the issue shown on your screenshot that why I am not really sure what I tried really work or not. The UI always scale properly on my end somehow.

**Comment by husseinraed** [comment]
its because of the window size ur not handling resizing sprites properly i guess try chaging ur window size to 1024 by 600

**Comment by husseinraed** [comment]
height 600 width 1024

**Comment by remance** [comment]
yeah, I tried that on the game config and get a similar result as yours now. at least my quick fix make the button show up with that resolution at least but my scale equation probably cause this problem.

**Comment by remance** [comment]
at least the battle ui still look fine with 1024 x 600 (phew), ok I will fix this problem. no worry :)

**Comment by remance** [comment]
![Untitled](https://user-images.githubusercontent.com/25480944/107983303-7a857200-6fbd-11eb-8126-2cb22eab7559.png)

**Comment by husseinraed** [comment]
oh ok i fixed the problem of the initial screen size but i have a problem look 
![image](https://user-images.githubusercontent.com/61946274/107983405-c42e8680-6fd6-11eb-839b-a5c0b8695046.png)

**Comment by husseinraed** [comment]
basically i made instead of statically settign the screen size for the game it automatically sets one depending on the screensize
but im getting this error huh

**Comment by remance** [comment]
did you delete this line in main.py? :    Soundvolume = float(config['DEFAULT']['SoundVolume'])

**Comment by remance** [comment]
it used to be like this:

    ScreenHeight = int(config['DEFAULT']['ScreenHeight'])
    ScreenWidth = int(config['DEFAULT']['ScreenWidth'])
    FULLSCREEN = int(config['DEFAULT']['Fullscreen'])
    Soundvolume = float(config['DEFAULT']['SoundVolume'])
    Profilename = str(config['DEFAULT']['playername'])

**Comment by remance** [comment]
yeah when I comment that line out I get your error.

**Comment by husseinraed** [comment]
no no no infact look 
![image](https://user-images.githubusercontent.com/61946274/107983651-44ed8280-6fd7-11eb-9d5f-ac6ff300cbe4.png)

**Comment by remance** [comment]
mhmm ok this is weird.  can you put up pull request? I will have a full look.

**Comment by husseinraed** [comment]
ok

**Comment by husseinraed** [comment]
OOH LOL heres the error 
theres an error occuring in my code that i added basically llook

**Comment by husseinraed** [comment]
![image](https://user-images.githubusercontent.com/61946274/107983790-972ea380-6fd7-11eb-83ab-6c819571c60d.png)

**Comment by husseinraed** [comment]
my code is producing float numbers

**Comment by husseinraed** [comment]
ill fix it with floor division `//`

**Comment by remance** [comment]
ah lol ok :P

**Comment by husseinraed** [comment]
xd, im actually having fun helping you in this

**Comment by remance** [comment]
haha well glad to hear :) and thanks. Hopefully, you will like the game when it gets full 1.0 release. still a long way from finish.

**Comment by husseinraed** [comment]
yes

**Comment by husseinraed** [comment]
i fixed it ill send a pull request so u can merge the code

**Comment by husseinraed** [comment]
sent it 👍🏻

**Comment by husseinraed** [comment]
u can try it just delete the configuration.ini and run main.py

**Comment by remance** [comment]
This manage to fix even the small resolution problem?

**Comment by husseinraed** [comment]
its perfect

it basically when u first run the game sets the resulotion of ur window to ur screen res

![image](https://user-images.githubusercontent.com/61946274/107984227-8a5e7f80-6fd8-11eb-8943-7ac3d10b1027.png)

it fixed my issue too

**Comment by remance** [comment]
ah, that's superb. Thanks again.

**Comment by husseinraed** [comment]
![image](https://user-images.githubusercontent.com/61946274/107984261-a06c4000-6fd8-11eb-8ba2-efe507acb29a.png)

**Comment by husseinraed** [comment]
np

**Comment by husseinraed** [comment]
lets close this issue now

**Comment by remance** [comment]
ok gotta add dependency for screeninfo as well, I will do that

**Comment by husseinraed** [comment]
i did that in requirements.txt
