### ISSUE TITLE
error

### ISSUE THREAD

**Issue by NOTSN** [remance/Masendor#13]
File "D:\Masendor-master\gamescript\gameunitstat.py", line 169, in __init__
    for row in rd:
UnicodeDecodeError: 'gbk' codec can't decode byte 0x94 in position 47: illegal multibyte sequence

**Comment by remance** [comment]
Thank you for posting the issue. This is quite a bit weird error. I am guessing that this is the problem with system locale. I try fixing this issue by specify all encoding with UTF-8 in the new update. Can you help check whether the update fix this issue?

**Comment by remance** [comment]
This issue is likely fixed by now.
