### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by legotrainkid** [remance/Masendor#2]
When I try and run the mainmenu.py script from the python IDLE, it throws an error saying:
Traceback (most recent call last):
  File "C:\Users\legot\Documents\GitHub\Masendor\mainmenu.py", line 11, in <module>
    from RTS import maingame
ModuleNotFoundError: No module named 'RTS'

Am I running the game wrong, or is it an actual problem in the code?

**Comment by remance** [comment]
Ah yike I forgot to change the RTS folder into reading whatever the folder name of the game. Well for now just change the game folder name to RTS and it should work. I will fix this in the next update.

**Comment by remance** [comment]
Thank you for pointing this out, legotrainkid. I fix this issue with the new update.
