### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Hamster-lord** [remance/Masendor#23]
File "/Users/Emma/PycharmProjects/Madendor/Masendor-0.6.2.1/gamescript/gamelongscript.py", line 591, in csv_read
    with open(main_dir + folderlist, encoding="utf-8", mode="r") as unitfile:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/Emma/PycharmProjects/Madendor/Masendor-0.6.2.1/gamescript/data/ruleset/historical/map//Users/Emma/PycharmProjects/Madendor/Masendor-0.6.2.1/gamescript/data/ruleset/historical/map/megiddo/info.csv'

**Comment by Hamster-lord** [comment]
Thx Also do I need to download all the files in the new realease or 1 or 2. If it is 1 or 2 please tell me which ones

**Comment by Hamster-lord** [comment]
Also do I need to use pycharm pro or can I use Pycharm community.

**Comment by remance** [comment]
If you are going to test the release, then you need all the files in that version. Unless you are talking about the commit then just clone the repo will work.

For pycharm, you only need it for testing the commit update and you can use either version as long as it use python 3.10.

**Comment by Hamster-lord** [comment]
ok thx

**Comment by Hamster-lord** [comment]
Can I use 3.8?

**Comment by remance** [comment]
3.8 may still work but 3.10 work for sure.
