### ISSUE TITLE
issue #2

### ISSUE THREAD

**Issue by Hamster-lord** [remance/Masendor#24]
File "/Users/Emma/PycharmProjects/Madendor/Masendor-0.6.2.3 3/gamescript/gamesubunit.py", line 1046, in update
    self.melee_target = self.parentunit.attack_target.subunit_sprite[0]

**Comment by remance** [comment]
Do you know when this error occur? like when unit collide or retreat.

**Comment by Hamster-lord** [comment]
I don't know there was a battle and a lot of fighting, but some of the people were running away

**Comment by remance** [comment]
Probably still existed in the newest version. I will keep this open for now.

**Comment by remance** [comment]
From the look of it this issue should be fixed now.
