### ISSUE TITLE
issue #3

### ISSUE THREAD

**Issue by Hamster-lord** [remance/Masendor#25]

**Comment by Hamster-lord** [comment]
File "/Users/Emma/PycharmProjects/Madendor/Masendor-0.6.2.3 3/gamescript/gamesubunit.py", line 1176, in update
    gamerangeattack.Rangearrow(self, self.base_pos.distance_to(self.attack_pos), self.shootrange, self.zoom)  # Shoot
TypeError: a sequence is expected

**Comment by Hamster-lord** [comment]
This happened when I clicked the minus sign to slow down the game

**Comment by remance** [comment]
Thank you for the report. Seem like this issue is prevalent in the newest update as well. I will have a look for next update.

**Comment by remance** [comment]
This issue should now be fixed in the new update.
