### ISSUE TITLE
Map editor issue

### ISSUE THREAD

**Issue by Hamster-lord** [remance/Masendor#26]
File "/Users/Emma/PycharmProjects/Madendor/Masendor-0.6.2.3 3/gamescript/gamelongscript.py", line 594, in csv_read
    with open(main_dir + folderlist, encoding="utf-8", mode="r") as unitfile:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/Emma/PycharmProjects/Madendor/Masendor-0.6.2.3 3/data/ruleset/historical/map/custom//Users/Emma/PycharmProjects/Madendor/Masendor-0.6.2.3 3/data/ruleset/historical/map/custom/grassland/info.csv'

**Comment by remance** [comment]
Thanks for the report, map editor and custom map is not a working feature yet. So the error is expected (probably should disable it entirely for now).

**Comment by remance** [comment]
This feature is disabled for now.
