### ISSUE TITLE
Issue that I'm pretty sure is ok

### ISSUE THREAD

**Issue by Hamster-lord** [remance/Masendor#29]
Unit editor and army editor nnno work

**Comment by remance** [comment]
Unit editor is currently disabled for bug fixing. Army editor is not implemented yet. Will let you know when unit editor is working again.

**Comment by Hamster-lord** [comment]
ok thx

**Comment by Hamster-lord** [comment]
also in tactical mode there are a lot of errors and in arcade mode how to attack and when be soldiers are next to the enemy I can't get to to retreat including my own guy :(

**Comment by remance** [comment]
Can you post what kind of error occur when you test tactical mode? For the arcade mode, actually working on that right now. At the moment, arcade mode attack only work for range weapon.

**Comment by Hamster-lord** [comment]
2022-12-20 21:25 -- Empty method is called
/Users/Emma/Documents/GitHub/Masendor/gamescript/common/battle/generate_unit.pyAt Line35:generate_unit2022-12-20 21:25 -- Empty method is called
/Users/Emma/Documents/GitHub/Masendor/gamescript/common/battle/generate_unit.pyAt Line35:generate_unit2022-12-20 21:25 -- Empty method is called
/Users/Emma/Documents/GitHub/Masendor/gamescript/common/battle/generate_unit.pyAt Line35:generate_unit2022-12-20 21:25 -- Empty method is called
/Users/Emma/Documents/GitHub/Masendor/gamescript/common/battle/generate_unit.pyAt Line35:generate_unit2022-12-20 21:25 -- Empty method is called
/Users/Emma/Documents/GitHub/Masendor/gamescript/common/battle/generate_unit.pyAt Line35:generate_unit2022-12-20 21:25 -- Empty method is called
/Users/Emma/Documents/GitHub/Masendor/gamescript/common/battle/generate_unit.pyAt Line35:generate_unit2022-12-20 21:25 -- Empty method is called
/Users/Emma/Documents/GitHub/Masendor/gamescript/common/battle/generate_unit.pyAt Line35:generate_unit2022-12-20 21:25 -- Empty method is called
/Users/Emma/Documents/GitHub/Masendor/gamescript/common/battle/generate_unit.pyAt Line35:generate_unit2022-12-20 21:25 -- Empty method is called
/Users/Emma/Documents/GitHub/Masendor/gamescript/common/battle/generate_unit.pyAt Line35:generate_unit2022-12-20 21:25 -- Empty method is called
/Users/Emma/Documents/GitHub/Masendor/gamescript/common/battle/generate_unit.pyAt Line35:generate_unit2022-12-20 21:25 -- Empty method is called
/Users/Emma/Documents/GitHub/Masendor/gamescript/common/battle/generate_unit.pyAt Line35:generate_unit2022-12-20 21:25 -- Empty method is called
/Users/Emma/Documents/GitHub/Masendor/gamescript/common/battle/generate_unit.pyAt Line35:generate_unit2022-12-20 21:25 -- Empty method is called
/Users/Emma/Documents/GitHub/Masendor/gamescript/common/battle/generate_unit.pyAt Line35:generate_unit2022-12-20 21:25 -- Empty method is called
/Users/Emma/Documents/GitHub/Masendor/gamescript/common/battle/generate_unit.pyAt Line35:generate_unit2022-12-20 21:25 -- Empty method is called
/Users/Emma/Documents/GitHub/Masendor/gamescript/common/battle/generate_unit.pyAt Line35:generate_unit2022-12-20 21:25 -- Empty method is called
/Users/Emma/Documents/GitHub/Masendor/gamescript/common/battle/generate_unit.pyAt Line35:generate_unit2022-12-20 21:25 -- Empty method is called
/Users/Emma/Documents/GitHub/Masendor/gamescript/common/battle/generate_unit.pyAt Line35:generate_unit2022-12-20 21:25 -- Empty method is called
/Users/Emma/Documents/GitHub/Masendor/gamescript/common/battle/generate_unit.pyAt Line35:generate_unit2022-12-20 21:25 -- Empty method is called
/Users/Emma/Documents/GitHub/Masendor/gamescript/common/battle/generate_unit.pyAt Line35:generate_unit2022-12-20 21:25 -- Empty method is called
/Users/Emma/Documents/GitHub/Masendor/gamescript/common/battle/generate_unit.pyAt Line35:generate_unit!! Traceback (most recent call last):
!!   File "/Users/Emma/Documents/GitHub/Masendor/main.py", line 12, in <module>
    runmenu = game.Game(main_dir, error_log)
!!   File "/Users/Emma/Documents/GitHub/Masendor/gamescript/game.py", line 718, in __init__
    self.run()
!!   File "/Users/Emma/Documents/GitHub/Masendor/gamescript/game.py", line 1113, in run
    self.menu_team_select(mouse_left_up, mouse_left_down, mouse_scroll_up, mouse_scroll_down, esc_press)
!!   File "/Users/Emma/Documents/GitHub/Masendor/gamescript/common/game/menu_team_select.py", line 78, in menu_team_select
    self.start_battle()
!!   File "/Users/Emma/Documents/GitHub/Masendor/gamescript/common/game/start_battle.py", line 11, in start_battle
    self.battle_game.run_game()
!!   File "/Users/Emma/Documents/GitHub/Masendor/gamescript/battle.py", line 942, in run_game
    self.subunit_updater.update(self.current_weather, self.dt, self.camera_zoom,
!!   File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pygame/sprite.py", line 539, in update
    sprite.update(*args, **kwargs)
!!   File "/Users/Emma/Documents/GitHub/Masendor/gamescript/subunit.py", line 588, in update
    self.status_update(weather=weather)
!!   File "/Users/Emma/Documents/GitHub/Masendor/gamescript/common/subunit/status_update.py", line 207, in status_update
    self.special_effect[effect][0][1] = True
!! KeyError: 2

**Comment by remance** [comment]
Seem like this is error from older version. The newest commit update should already fix it.

**Comment by Hamster-lord** [comment]
where is it?

**Comment by Hamster-lord** [comment]
oh dound it but it says

**Comment by Hamster-lord** [comment]
!! Traceback (most recent call last):
!!   File "/Users/Emma/Documents/GitHub/Hampter/main.py", line 12, in <module>
    game.Game(main_dir, error_log)
!!   File "/Users/Emma/Documents/GitHub/Hampter/gamescript/game.py", line 576, in __init__
    subunit_ui_images |= new_subunit_ui_images
!! TypeError: unsupported operand type(s) for |=: 'dict' and 'dict'

**Comment by Hamster-lord** [comment]
uh hello?

**Comment by remance** [comment]
Sorry for the delay. Not quite certain what cause this error but the newest update should fix it.

**Comment by Hamster-lord** [comment]
still no work

**Comment by Hamster-lord** [comment]
!! Traceback (most recent call last):
!!   File "/Users/Emma/Documents/GitHub/Hampter/main.py", line 12, in <module>
    game.Game(main_dir, error_log)
!!   File "/Users/Emma/Documents/GitHub/Hampter/gamescript/game.py", line 716, in __init__
    self.change_game_genre(self.genre)
!!   File "/Users/Emma/Documents/GitHub/Hampter/gamescript/game.py", line 1004, in change_game_genre
    self.change_ruleset()
!!   File "/Users/Emma/Documents/GitHub/Hampter/gamescript/game.py", line 776, in change_ruleset
    self.troop_animation = datasprite.TroopAnimationData(self.main_dir,
!!   File "/Users/Emma/Documents/GitHub/Hampter/gamescript/datasprite.py", line 197, in __init__
    imgs = load_textures(main_dir,
!!   File "/Users/Emma/Documents/GitHub/Hampter/gamescript/common/utility.py", line 113, in load_textures
    load_order_file.sort(key=lambda var: [int(x) if x.isdigit() else x for x in re.findall(r"[^0-9]|[0-9]+", var)])
!! TypeError: '<' not supported between instances of 'str' and 'int'

**Comment by remance** [comment]
Can you try update the project again? the newer version doesn't use load_textures function anymore, so the one you are using seem to still be the old version I think. 

![image](https://user-images.githubusercontent.com/25480944/209584213-eadec8fd-fa5b-4963-aefc-8994880533d0.png)

Just press on the update button if you are running it on pycharm.

**Comment by Hamster-lord** [comment]
same error

**Comment by Hamster-lord** [comment]
I will just restart everything

**Comment by Hamster-lord** [comment]
It works now

**Comment by remance** [comment]
ah ok great to hear.

**Comment by Hamster-lord** [comment]
:p

**Comment by Hamster-lord** [comment]
question: How old are you?

**Comment by Hamster-lord** [comment]
This crazy for someone young so I'm just asking and you should publish this when your done

**Comment by Hamster-lord** [comment]
what is "Invalid path to Command Line Tools"

**Comment by remance** [comment]
This error in pycharm? https://github.com/emory-courses/dsa-java/issues/13

**Comment by Hamster-lord** [comment]
![Uploading Screen Shot 2022-12-28 at 9.26.02 AM.png…]()

**Comment by Hamster-lord** [comment]
what to do?

**Comment by remance** [comment]
This issue seem to be only on macOS. I am not perfectly certain if I know the fix to your issue but from looking around. 

This may fix it : https://stackoverflow.com/questions/47441949/error-running-git-in-pycharm-after-recent-update

So just run "xcode-select --install" on pycharm terminal 

![image](https://user-images.githubusercontent.com/25480944/209882480-c6fdca74-73bc-45c0-b27f-2e5d4bc10ef5.png)

**Comment by Hamster-lord** [comment]
I got this

**Comment by Hamster-lord** [comment]
xcode-select: error: command line tools are already installed, use "Software Update" to install updates

**Comment by Hamster-lord** [comment]
When I try to update I get

**Comment by Hamster-lord** [comment]
7:07 p.m.	Cannot Run Git
				Invalid path to Command Line Tools
				Fix Path

7:07 p.m.	Update canceled

**Comment by Hamster-lord** [comment]
Also what works in the thing? Because some of the things I'm trying to use cause an error

**Comment by remance** [comment]
Does this issue occur after you update your os? Seem like it is common for every macOS update. 

https://apple.stackexchange.com/questions/254380/why-am-i-getting-an-invalid-active-developer-path-when-attempting-to-use-git-a

Another suggestion is to run sudo xcode-select --reset then do xcode-select --install again

**Comment by Hamster-lord** [comment]
why does it want a password for the second one?

**Comment by remance** [comment]
Unfortunately I have no idea. It is probably easier to just reinstall pycharm/git I would guess.

**Comment by Hamster-lord** [comment]
Oh I just needed to update my computer

**Comment by remance** [comment]
Nice. Seem like macOS is a bit troublesome to use for these kinds of stuff it seem.

**Comment by Hamster-lord** [comment]
yeah
