### ISSUE TITLE
'Unsupported operand type(s)' Error

### ISSUE THREAD

**Issue by stefanwerleman** [remance/Masendor#33]
I'm trying to run the `main.py` script locally on my machine and I'm receiving this exception after running `python3 main.py`:
![image](https://user-images.githubusercontent.com/54635363/222456824-cc7b49a7-7537-4987-b904-1cc08dd7ed46.png)

**Python Version:** 3.8.10
**OS:** Ubuntu (Mint Distro)

**Comment by remance** [comment]
Thank you for the report. You need python 3.10 to run this game. Will add a check and error warning for this in the next update.

**Comment by remance** [comment]
Added a warning in the newest update for incompatible python version.
