### ISSUE TITLE
main.spec seems to reference files you didnt put on github,

### ISSUE THREAD

**Issue by twobob** [remance/Masendor#67]
25313 INFO: Appending 'datas' from .spec
Unable to find "c:\REPO\Masendor\gamescript" when adding binary and data files.

**Comment by twobob** [comment]
datas += [('data', 'data'), ('engine', 'engine'), ('animation-maker', 'animation-maker'), ('photo-studio', 'photo-studio')]
probably

**Comment by remance** [comment]
Thanks for the fix. It was the old file naming format I forgot to change in main.spec.
